### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dinoba**
storm-starter  example topology - namespace fix

### CODE REVIEW

**Comment by erikdw** [comment]
Please improve the commit message to say something about *what* is being updated.

**Comment by dinoba** [comment]
OK, comment edited.

**Comment by erikdw** [comment]
Sorry @dinoba : I meant the commit message and the PR title.

**Comment by erikdw** [comment]
@dinoba : I hope you understand where I'm coming from, I'm not trying to deny this PR by any means.  I just want our commit messages to be meaningful.  It's really important for maintainability to keep commits clean and nicely documented.

**Comment by dinoba** [comment]
I got that, just couldn't find way to change commit msg. And I was in hurry.

**Comment by erikdw** [comment]
@dinoba : ahhh, so you're not a git expert yet.  No worries, I avoided creating a branch for like 1.5 years when I first started using git, we're all at different stages of our journeys in git-land.

The answer for "how to change a commit message" is:

1. Modify the message within your local repo/branch.
  * If the commit message you want to change is the latest one, then you can just do:  `git commit --amend`, which opens an editor for you to modify the message.
  * If it's not the latest commit, then you can use `git rebase -i HEAD~N`, where `N` is the number back the commit is from being latest (3rd latest commit --> use 3 as `N`).  Then you change `pick` to `reword` for the appropriate commit, then save and quit, this will trigger the git to open another editor for you to modify the commit message.
2. Forcefully push the changes to the remote using `git push -f`.  This is necessary because you are rewriting the history of your branch, so the remote repo needs to be overwritten instead of just appended to.

You should also "squash" those 2 commits into one, get rid of the trailing whitespace, and also fix the spelling of "apropriate".   Squashing can be done similarly to the steps above using rebase:
* https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by dinoba** [comment]
Problem is that I was doing this online :) using github inline editor.
I will create local repo, push new commit and you can deny this change.

**Comment by erikdw** [comment]
@dinoba : ohhhh, the editing fanciness within the github UI!! Gotcha...  ok, cool.  I'll review the new PR when you send it, and link to this one.

**Pull request closed without merging**
