### PR TITLE
Prevent supervisor suicide epidemic

### LINKED ISSUE #202: Storm 1.0.3 Support - MesosSupervisor Committing Suicide
Hi, All. Tremendous work in getting Storm 1.x support with this framework. So far so good with 1.0.2; thank you everyone for your contributions.

I've attempted to drop in Storm 1.0.3 and ran into an issue which I think is ultimately related to a refactor of converting some clojure code to java in the storm project, specifically the Supervisor (https://issues.apache.org/jira/browse/STORM-2018)

What's happening is that by upgrading to Storm 1.0.3 the "assigned" method is no longer being called, as a result, the MesosSupervisor is not updating its internal view of '_supervisorViewOfAssignedPorts' and is committing suicide:
*  https://github.com/mesos/storm/blob/9911151a0efb78203f14456b7873f94fbe5b64b5/storm/src/main/storm/mesos/MesosSupervisor.java#L261

I patched this locally, by calling the 'assigned' method from the 'confirmAssigned' method which gets called at the same frequency as 1.0.2 was calling assigned. This fixes the issue and I can put in a PR for this, but I'm wondering if folks have some context as to why assigned is no longer being called and that if this change could have unintended consequences.

Here's some stacks of the calls in 1.0.2 vs 1.0.3 (I just threw exceptions in the code, and printed the trace):

1.0.2:

```
2017-07-21 21:51:15.616 s.m.MesosSupervisor [INFO] confirmAssigned, stack = java.lang.Throwable
	at storm.mesos.MesosSupervisor.confirmAssigned(MesosSupervisor.java:114)
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9163$fn__9167.invoke(supervisor.clj:548)
	at org.apache.storm.util$filter_key$fn__469.invoke(util.clj:318)
	at clojure.core$filter$fn__4580.invoke(core.clj:2690)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
	at clojure.core.protocols$fn__6506.invoke(protocols.clj:101)
	at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6519)
	at clojure.core$into.invoke(core.clj:6600)
	at org.apache.storm.util$filter_key.invoke(util.clj:318)
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9163.invoke(supervisor.clj:548)
	at org.apache.storm.event$event_manager$fn__8735.invoke(event.clj:40)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)

2017-07-21 21:51:15.617 s.m.MesosSupervisor [INFO] assigned = [31001]
2017-07-21 21:51:15.618 s.m.MesosSupervisor [INFO] assigned, stack = java.lang.Throwable
	at storm.mesos.MesosSupervisor.assigned(MesosSupervisor.java:72)
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9163.invoke(supervisor.clj:592)
	at org.apache.storm.event$event_manager$fn__8735.invoke(event.clj:40)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

1.0.3 (with my patch where confirmAssigned calls assigned):
```
2017-07-21 22:06:12.003 o.a.s.d.s.Supervisor [INFO] Starting supervisor with id foo at host alphab-bvlt-r1n89.
2017-07-21 22:06:12.941 s.m.MesosSupervisor [INFO] getMetadata: ports = [31000]
2017-07-21 22:06:13.015 s.m.MesosSupervisor [INFO] confirmAssigned: port = 31000
2017-07-21 22:06:13.017 s.m.MesosSupervisor [INFO] confirmAssigned, stack = java.lang.Throwable
	at storm.mesos.MesosSupervisor.confirmAssigned(MesosSupervisor.java:123)
	at org.apache.storm.daemon.supervisor.ReadClusterState.run(ReadClusterState.java:143)
	at org.apache.storm.event.EventManagerImp$1.run(EventManagerImp.java:54)

2017-07-21 22:06:13.017 s.m.MesosSupervisor [INFO] assigned: ports = 
2017-07-21 22:06:13.017 s.m.MesosSupervisor [INFO] assigned, stack = java.lang.Throwable
	at storm.mesos.MesosSupervisor.assigned(MesosSupervisor.java:80)
	at storm.mesos.MesosSupervisor.confirmAssigned(MesosSupervisor.java:127)
	at org.apache.storm.daemon.supervisor.ReadClusterState.run(ReadClusterState.java:143)
	at org.apache.storm.event.EventManagerImp$1.run(EventManagerImp.java:54)

2017-07-21 22:06:13.020 o.a.s.d.s.Slot [WARN] SLOT alphab-bvlt-r1n89:31000 Starting in state EMPTY - assignment null
2017-07-21 22:06:13.030 o.a.s.d.s.Slot [INFO] STATE EMPTY msInState: 10 -> WAITING_FOR_BASIC_LOCALIZATION msInState: 0
2017-07-21 22:06:13.128 o.a.s.u.NimbusClient [INFO] Found leader nimbus : alphab-bvlt-r1n85:31075
2017-07-21 22:06:13.592 s.m.MesosSupervisor [INFO] SuicideDetector: _supervisorViewOfAssignedPorts = [31000], now = 1500674773592, _lastTime = 1500674768591
```

### PR DESCRIPTION
**Pull request by erikdw**
Fixes #202.  These changes are all by @michaelmoss, and this was all reviewed and tested in #204, I'm just creating a new PR with a clean commit history so I can merge it straight away.

### CODE REVIEW

**Comment by erikdw** [comment]
Thanks @michaelmoss for the work on this and dealing with all the follow-ups!

**Comment by erikdw** [comment]
Notably, this PR breaks support for Storm 1.0.0, 1.0.1, and 1.0.2 in this project.  We've intentionally done this so that forward progress can be made.

**Comment by JessicaLHartog** [comment]
@erikdw Should we tag just before this set of commits so that it's easier for users of Storm 1.0.[0..2] can more readily leverage this project? Or do you think the release before this sufficient?

**Comment by erikdw** [comment]
@JessicaLHartog : good idea.  Let's think about what to call the name, we can always tag a previous commit later:
* https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git

I'm going to try to generate a new build from this, and then merge in your scheduling change (#200).

**Comment by erikdw** [comment]
v0.2.3 released:
* https://github.com/mesos/storm/releases/tag/v0.2.3

**Pull request merged**
