### PR TITLE
use value of RELEASE environment variable if already set

### PR DESCRIPTION
**Pull request by salimane**

### CODE REVIEW

**Comment by erikdw** [comment]
@salimane : makes sense to me.  I haven't yet built with this, give me a day to test it please.  (Well, we have to wait for @tnachen anyways, 'cause I don't have push perms yet ;-) )

**Comment by erikdw** [comment]
@salimane : I was unfamiliar with the `:` bash syntax.  Are you ok with changing this to be more like the MIRROR line below it?  i.e.,

```shell
RELEASE=${RELEASE:-`grep -1 -A 0 -B 0 '<version>' pom.xml | head -n 1 | awk '{print $1}' | sed -e 's/.*<version>//' | sed -e 's/<\/version>.*//'`}
```

**Comment by salimane** [comment]
@erikdw done :)

**Comment by erikdw** [comment]
@salimane : thanks! (And I appreciate the additional newline beforehand to make the file look better!)

@tnachen or @brndnmtthws : when you get a chance can you please merge @salimane 's change?

**Comment by brndnmtthws** [comment]
Looks good, thanks!

**Comment by erikdw** [comment]
thanks @salimane & @brndnmtthws !

**Pull request merged**
